### ISSUE TITLE
Gulp error

### ISSUE THREAD

**Issue by Ibochkarev** [HosseinKarami/fastshell#19]
```i.bochkarev@Mac-mini-Ivan  ~/Desktop/tmp/fastshell   master ●  sudo gulp
assert.js:350
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/Users/i.bochkarev/Desktop/tmp/fastshell/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/Users/i.bochkarev/Desktop/tmp/fastshell/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/Users/i.bochkarev/Desktop/tmp/fastshell/gulpfile.js:68:6)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)```

**Comment by aage21** [comment]
im having this same error. what did you do to solve it? 

thanks

**Comment by Ibochkarev** [comment]
Please close error. Thanks

**Comment by lblanton** [comment]
I am having the same issue. It seems to be with the Undertaker plugin. What does that do and how can this be corrected? I see it's a dependency, so it obviously can't just be removed.

**Comment by lblanton** [comment]
> Please close error. Thanks

@Ibochkarev How did you fix it since you have closed the issue? I am having the same problem as of 11/10/2018.

**Comment by Ibochkarev** [comment]
> > Please close error. Thanks
> 
> @Ibochkarev How did you fix it since you have closed the issue? I am having the same problem as of 11/10/2018.

Hello.
I updated gulp to version 4. And because of this, gulp stopped running. It was necessary to rewrite the config. Removed the arrow for updating the packages.json version and everything is ok
